// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCNHRtAqfaUsItruby0g7I6Oizvh4cad0',
    appId: '1:127342166234:web:923a98b9c70a41524565e3',
    messagingSenderId: '127342166234',
    projectId: 'sodaproject-20527',
    authDomain: 'sodaproject-20527.firebaseapp.com',
    databaseURL:
        'https://sodaproject-20527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sodaproject-20527.appspot.com',
    measurementId: 'G-DBFEBFC8KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_v7G9QMsyEduYBl_MkJsKNcn1SYuw0PE',
    appId: '1:127342166234:android:1e3e74370b580f874565e3',
    messagingSenderId: '127342166234',
    projectId: 'sodaproject-20527',
    databaseURL:
        'https://sodaproject-20527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sodaproject-20527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0ygvXM7rsEhIw69c-gmqQk0t3DUHiT4',
    appId: '1:127342166234:ios:1cc2e0953d52ced54565e3',
    messagingSenderId: '127342166234',
    projectId: 'sodaproject-20527',
    databaseURL:
        'https://sodaproject-20527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sodaproject-20527.appspot.com',
    iosClientId:
        '127342166234-uu9s2paqmbcl3epep7bqlb8patqg81o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sodaproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0ygvXM7rsEhIw69c-gmqQk0t3DUHiT4',
    appId: '1:127342166234:ios:1cc2e0953d52ced54565e3',
    messagingSenderId: '127342166234',
    projectId: 'sodaproject-20527',
    databaseURL:
        'https://sodaproject-20527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sodaproject-20527.appspot.com',
    iosClientId:
        '127342166234-uu9s2paqmbcl3epep7bqlb8patqg81o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sodaproject',
  );
}
